### PR TITLE
improve closure example

### PR DESCRIPTION
**Pull request by gaboesquivel**
improve the closure example, currently it's more a global var than closure

### CODE REVIEW

**Comment by stevengpa** [comment]
Hi my friend,

Thank you so much for your feedback, I did change the Closure example because you are right, the example is not clear :), in the other hand, I think your example is ok but It is pretty much Currying than Closure:

``` javascript
// Currying
function Multiplier(m) {
  return function (n) {
    return n * m;
  }
}
```

Blog post about Currying: https://medium.com/@kbrainwave/currying-in-javascript-ce6da2d324fe

**Comment by gaboesquivel** [comment]
Hey, you are right. Perhaps this simpler example works better 

``` js
var print = (function(){
  var h = 'hola';
  function printH(){
    console.log(h);
  }
  return printH;
})();

print(); // =>  'hola'
```

Or

``` js
function CustomLogger(){
  var prefix = 'Logger: ';
  function log(msg){
    console.log(prefix +  msg);
  }
  return{
    log: log
  }
}

var logger = CustomLogger();
logger.log('logging...');
```

**Comment by stevengpa** [comment]
Totally agree my friend, we could proceed with one of your examples in two ways:

1) Could you please submit a pull request with the example?
2) I include your example in the doc

It would be great if you choose the first one :)

**Comment by gaboesquivel** [comment]
Ready, squashed the update on the PR.  I prefer the first one as well.  
I'm forking out you repo on CostaRicaJS... that's intended to be Spanish only 
https://github.com/CostaRicaJS/Fundamentos-de-JavaScript

**Comment by stevengpa** [comment]
Awesome ! :)

**Pull request merged**
